name: Deploy

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo pip install -r requirements.txt  # Install dependencies from requirements.txt.
        sudo python app.py &
  test:
    runs-on: ubuntu-latest
    needs: build

    outputs:
      tests_passed: ${{ steps.test_result.outputs.tests_passed }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo pip install -r requirements.txt  # Install dependencies from requirements.txt
    - name: Run tests
      id: test_result
      run: |
        # Execute your testing scripts, assuming pytest is used
        pytest test_app.py
        echo "::set-output name=tests_passed::true"  # Set the output if tests pass
        continue-on-error: true  # Continue even if tests fail

    - name: Deploy to main branch
      run: |
        repo_path="/home/ubuntu/CICD_GitActions"
        staging_branch="staging"
        main_branch="main"

        cd "$repo_path"
        sudo git config pull.rebase true
        sudo git fetch origin "$staging_branch"
        sudo git pull --rebase origin "$staging_branch"

        sudo git rebase "origin/$staging_branch"
        sudo git config pull.rebase true

        if [[ $(git status | grep 'modified:' | wc -l) -ne 0 ]]; then
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install -r requirements.txt

          nohup python app.py &&
          pytest test_app.py

          git add .
          git commit -m "Code is modified"
          git push origin "$staging_branch":"$main_branch" --force-with-lease

          echo "Changes pushed to $main_branch branch."
        else
          echo "No code changes detected. Skipping deployment."
        fi
