name: Deploy to ec2 instance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code base
        uses: actions/checkout@v4
